#!/usr/bin/env bash
# Build a Porteus module for aufs-dir-tools

pkg_name="aufs-dir-tools"
pkg_version="0.0.2dev"
pkg_arch="noarch"

if ! which dir2xzm; then
	echo "dir2xzm not found. Are you on Porteus?"
	exit 1
fi

pushd "$(dirname "$(realpath "$0")")" &>/dev/null || exit 1
dir2xzm dist/ "${pkg_name}-${pkg_version}-${pkg_arch}.xzm"
popd &>/dev/null
